"""
完整题库扩充 第3部分 — 变化的科学、抽象推理、高等数学
"""

FULL_QUIZ_3 = {
    "t21": [
        {"question": "从(1,2)到(4,8)的斜率是？", "options": ["1", "2", "3", "6"], "answer": 1, "explanation": "k = (8-2)/(4-1) = 6/3 = 2。"},
        {"question": "y = 3x + 1 的斜率是？", "options": ["1", "2", "3", "4"], "answer": 2, "explanation": "k = 3。"},
        {"question": "水平线的斜率是？", "options": ["0", "1", "-1", "不存在"], "answer": 0, "explanation": "水平线 Δy=0，k=0。"},
        {"question": "竖直线的斜率是？", "options": ["0", "1", "-1", "不存在"], "answer": 3, "explanation": "竖直线 Δx=0，分母为 0。"},
        {"question": "斜率的物理意义是？", "options": ["速度", "加速度", "变化率", "距离"], "answer": 2, "explanation": "斜率表示 y 随 x 的变化率。"},
        {"question": "y = -2x 的斜率是？", "options": ["-2", "2", "0", "不存在"], "answer": 0, "explanation": "k = -2。"},
        {"question": "两平行线的斜率关系？", "options": ["相等", "互为倒数", "互为相反数", "乘积为-1"], "answer": 0, "explanation": "平行线斜率相等。"},
        {"question": "两垂直线的斜率关系？", "options": ["相等", "互为倒数", "互为相反数", "乘积为-1"], "answer": 3, "explanation": "垂直线斜率乘积为 -1。"},
        {"question": "k=0 的直线是？", "options": ["水平线", "竖直线", "斜线", "曲线"], "answer": 0, "explanation": "斜率为 0 是水平线。"},
        {"question": "斜率不存在的直线是？", "options": ["水平线", "竖直线", "斜线", "曲线"], "answer": 1, "explanation": "斜率不存在是竖直线。"},
        {"question": "平均变化率的公式是？", "options": ["Δx/Δy", "Δy/Δx", "x/y", "y/x"], "answer": 1, "explanation": "平均变化率 = Δy/Δx。"},
        {"question": "瞬时变化率是？", "options": ["平均变化率", "导数", "积分", "极限"], "answer": 1, "explanation": "瞬时变化率就是导数。"},
        {"question": "f(x)=x² 在 [1,3] 上的平均变化率是？", "options": ["2", "3", "4", "8"], "answer": 2, "explanation": "(9-1)/(3-1) = 8/2 = 4。"},
        {"question": "直线 y=2x+1 的倾斜角是？", "options": ["30°", "45°", "60°", "arctan2"], "answer": 3, "explanation": "倾斜角 = arctan(k) = arctan(2)。"},
        {"question": "倾斜角的范围是？", "options": ["0-90°", "0-180°", "0-360°", "-90°到90°"], "answer": 1, "explanation": "倾斜角 α ∈ [0°, 180°)。"},
        {"question": "k > 0 时倾斜角范围？", "options": ["0-45°", "0-90°", "90-180°", "45-90°"], "answer": 1, "explanation": "k > 0 时 0° < α < 90°。"},
        {"question": "k < 0 时倾斜角范围？", "options": ["0-90°", "90-180°", "180-270°", "270-360°"], "answer": 1, "explanation": "k < 0 时 90° < α < 180°。"},
    ],
    "t22": [
        {"question": "f(x) = c（常数）的导数是？", "options": ["c", "0", "1", "不存在"], "answer": 1, "explanation": "常数的导数为 0。"},
        {"question": "f(x) = x 的导数是？", "options": ["0", "1", "x", "x²"], "answer": 1, "explanation": "(x)' = 1。"},
        {"question": "f(x) = x³ 的导数是？", "options": ["x²", "2x²", "3x²", "3x³"], "answer": 2, "explanation": "(x³)' = 3x²。"},
        {"question": "f(x) = 1/x 的导数是？", "options": ["1/x²", "-1/x²", "ln(x)", "-1/x"], "answer": 1, "explanation": "(x⁻¹)' = -x⁻² = -1/x²。"},
        {"question": "f(x) = √x 的导数是？", "options": ["1/(2√x)", "√x", "2√x", "1/√x"], "answer": 0, "explanation": "(x^½)' = ½x^(-½) = 1/(2√x)。"},
        {"question": "f(x) = eˣ 的导数是？", "options": ["xeˣ⁻¹", "eˣ", "eˣ⁺¹", "ln(x)"], "answer": 1, "explanation": "(eˣ)' = eˣ。"},
        {"question": "f(x) = ln(x) 的导数是？", "options": ["1/x", "x", "eˣ", "ln(x)"], "answer": 0, "explanation": "(ln x)' = 1/x。"},
        {"question": "f(x) = sin(x) 的导数是？", "options": ["-sin(x)", "cos(x)", "-cos(x)", "tan(x)"], "answer": 1, "explanation": "(sin x)' = cos x。"},
        {"question": "f(x) = cos(x) 的导数是？", "options": ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"], "answer": 1, "explanation": "(cos x)' = -sin x。"},
        {"question": "f(x) = tan(x) 的导数是？", "options": ["cot(x)", "sec²(x)", "-csc²(x)", "cos²(x)"], "answer": 1, "explanation": "(tan x)' = sec²x = 1/cos²x。"},
        {"question": "[f(x)+g(x)]' = ?", "options": ["f'(x)+g'(x)", "f'(x)g'(x)", "f(x)g'(x)", "f'(x)/g'(x)"], "answer": 0, "explanation": "和的导数 = 导数的和。"},
        {"question": "[f(x)g(x)]' = ?", "options": ["f'(x)g'(x)", "f'g+fg'", "f'g-fg'", "f'/g'"], "answer": 1, "explanation": "乘法法则：(fg)' = f'g + fg'。"},
        {"question": "[f(g(x))]' = ?", "options": ["f'(g(x))", "f'(g(x))g'(x)", "f(g'(x))", "f'(x)g'(x)"], "answer": 1, "explanation": "链式法则：f'(g(x))·g'(x)。"},
        {"question": "二阶导数 f''(x) 表示？", "options": ["变化率", "变化率的变化率", "面积", "体积"], "answer": 1, "explanation": "二阶导数是导数的导数。"},
        {"question": "f''(x) > 0 说明函数？", "options": ["递增", "递减", "凹向上", "凹向下"], "answer": 2, "explanation": "二阶导大于 0，函数凹向上（有最小值）。"},
        {"question": "f''(x) < 0 说明函数？", "options": ["递增", "递减", "凹向上", "凹向下"], "answer": 3, "explanation": "二阶导小于 0，函数凹向下（有最大值）。"},
        {"question": "f(x)=x⁴ 的导数是？", "options": ["4x³", "x³", "4x⁴", "3x⁴"], "answer": 0, "explanation": "(x⁴)' = 4x³。"},
    ],
    "t23": [
        {"question": "极值点处导数？", "options": ["大于0", "小于0", "等于0", "不存在"], "answer": 2, "explanation": "极值点处 f'(x)=0（费马引理）。"},
        {"question": "f'(x)=0 的点叫？", "options": ["零点", "驻点", "拐点", "间断点"], "answer": 1, "explanation": "f'(x)=0 的点叫驻点（稳定点）。"},
        {"question": "驻点一定是极值点吗？", "options": ["是", "不是", "有时是", "不确定"], "answer": 1, "explanation": "不一定，如 f(x)=x³ 在 x=0。"},
        {"question": "f(x)=x² 的最小值在？", "options": ["x=-1", "x=0", "x=1", "不存在"], "answer": 1, "explanation": "f'(x)=2x=0，x=0，f''(0)=2>0，最小值。"},
        {"question": "f(x)=-x² 的最大值在？", "options": ["x=-1", "x=0", "x=1", "不存在"], "answer": 1, "explanation": "f'(x)=-2x=0，x=0，f''(0)=-2<0，最大值。"},
        {"question": "f(x)=x³-3x 在 [-2,2] 上的最大值是？", "options": ["-2", "0", "2", "4"], "answer": 2, "explanation": "f(-1)=2, f(1)=-2, f(-2)=-2, f(2)=2，最大值 2。"},
        {"question": "f(x)=x³-3x 在 [-2,2] 上的最小值是？", "options": ["-2", "0", "2", "4"], "answer": 0, "explanation": "最小值 -2。"},
        {"question": "递增区间上 f'(x)？", "options": [">0", "<0", "=0", "不确定"], "answer": 0, "explanation": "递增：f'(x) > 0。"},
        {"question": "递减区间上 f'(x)？", "options": [">0", "<0", "=0", "不确定"], "answer": 1, "explanation": "递减：f'(x) < 0。"},
        {"question": "拐点处 f''(x) = ?", "options": ["0", "1", "-1", "不存在"], "answer": 0, "explanation": "拐点处二阶导为 0 且变号。"},
        {"question": "优化问题用什么求？", "options": ["积分", "导数", "极限", "方程"], "answer": 1, "explanation": "用导数求极值来优化。"},
        {"question": "f(x)=x²-4x+5 的最小值是？", "options": ["0", "1", "2", "5"], "answer": 1, "explanation": "f'(x)=2x-4=0，x=2，f(2)=1。"},
        {"question": "f(x)=sin(x) 在 [0,π] 上的最大值是？", "options": ["0", "1/2", "1", "π"], "answer": 2, "explanation": "sin(π/2)=1，最大值。"},
        {"question": "f(x)=x+1/x (x>0) 的最小值是？", "options": ["1", "2", "3", "4"], "answer": 1, "explanation": "f'(x)=1-1/x²=0，x=1，f(1)=2。"},
        {"question": "闭区间上连续函数一定有？", "options": ["最大值", "最小值", "最大值和最小值", "不确定"], "answer": 2, "explanation": "最值定理：闭区间上连续函数必有最大值和最小值。"},
        {"question": "罗尔定理的条件是？", "options": ["连续", "可导", "f(a)=f(b", "以上都对"], "answer": 3, "explanation": "f在[a,b]连续，在(a,b)可导，f(a)=f(b)。"},
    ],
    "t24": [
        {"question": "∫x dx = ?", "options": ["x²", "x²/2 + C", "x + C", "1"], "answer": 1, "explanation": "∫x dx = x²/2 + C。"},
        {"question": "∫1 dx = ?", "options": ["0", "1", "x + C", "x²/2 + C"], "answer": 2, "explanation": "∫1 dx = x + C。"},
        {"question": "∫eˣ dx = ?", "options": ["xeˣ⁻¹", "eˣ + C", "eˣ", "ln(x) + C"], "answer": 1, "explanation": "∫eˣ dx = eˣ + C。"},
        {"question": "∫(1/x) dx = ?", "options": ["ln|x| + C", "1/x² + C", "-1/x + C", "x + C"], "answer": 0, "explanation": "∫(1/x) dx = ln|x| + C。"},
        {"question": "∫cos(x) dx = ?", "options": ["sin(x) + C", "-sin(x) + C", "cos(x) + C", "-cos(x) + C"], "answer": 0, "explanation": "∫cos x dx = sin x + C。"},
        {"question": "∫xⁿ dx = ? (n≠-1)", "options": ["xⁿ⁺¹/(n+1) + C", "nxⁿ⁻¹ + C", "xⁿ/n + C", "xⁿ⁺¹ + C"], "answer": 0, "explanation": "∫xⁿ dx = xⁿ⁺¹/(n+1) + C。"},
        {"question": "∫₀¹ x² dx = ?", "options": ["0", "1/3", "1/2", "1"], "answer": 1, "explanation": "[x³/3]₀¹ = 1/3。"},
        {"question": "∫₀² 3x dx = ?", "options": ["3", "4", "6", "12"], "answer": 2, "explanation": "[3x²/2]₀² = 6。"},
        {"question": "定积分的几何意义是？", "options": ["长度", "面积", "体积", "斜率"], "answer": 1, "explanation": "定积分表示曲线下的面积。"},
        {"question": "∫ₐᵇ f(x)dx = -∫ᵇₐ f(x)dx 说明？", "options": ["对称性", "方向性", "可加性", "线性"], "answer": 1, "explanation": "交换上下限，积分变号。"},
        {"question": "∫₀π sin(x) dx = ?", "options": ["0", "1", "2", "π"], "answer": 2, "explanation": "[-cos x]₀π = -cosπ+cos0 = 1+1 = 2。"},
        {"question": "偶函数在对称区间上的积分 = ?", "options": ["0", "2∫₀ᵃ", "∫₀ᵃ", "不确定"], "answer": 1, "explanation": "偶函数：∫₋ₐᵃ f(x)dx = 2∫₀ᵃ f(x)dx。"},
        {"question": "奇函数在对称区间上的积分 = ?", "options": ["0", "2∫₀ᵃ", "∫₀ᵃ", "不确定"], "answer": 0, "explanation": "奇函数在对称区间上积分为 0。"},
        {"question": "不定积分加 C 的原因是？", "options": ["习惯", "常数导数为0", "方便", "必须"], "answer": 1, "explanation": "常数的导数为 0，所以原函数有无穷多个。"},
        {"question": "积分中值定理说？", "options": ["存在一点等于平均值", "积分等于0", "函数连续", "函数可导"], "answer": 0, "explanation": "存在 ξ∈[a,b] 使得 ∫ₐᵇ f(x)dx = f(ξ)(b-a)。"},
        {"question": "∫(2x+1) dx = ?", "options": ["x²+x+C", "2x²+x+C", "x²+C", "2x+C"], "answer": 0, "explanation": "∫2x dx + ∫1 dx = x² + x + C。"},
    ],
    "t25": [
        {"question": "微积分基本定理的发现者是？", "options": ["欧拉", "牛顿和莱布尼茨", "高斯", "黎曼"], "answer": 1, "explanation": "牛顿和莱布尼茨独立发现。"},
        {"question": "F(x) = ∫ₐˣ f(t)dt，则 F'(x) = ?", "options": ["f(x)", "f(t)", "F(x)", "0"], "answer": 0, "explanation": "微积分基本定理第一部分。"},
        {"question": "∫ₐᵇ f(x)dx = F(b)-F(a) 中 F 是？", "options": ["f 的导数", "f 的原函数", "f 的积分", "f 本身"], "answer": 1, "explanation": "F 是 f 的一个原函数。"},
        {"question": "速度的积分等于？", "options": ["加速度", "位移", "力", "功"], "answer": 1, "explanation": "∫v(t)dt = s(t)。"},
        {"question": "位移的导数等于？", "options": ["加速度", "速度", "力", "面积"], "answer": 1, "explanation": "s'(t) = v(t)。"},
        {"question": "加速度的积分等于？", "options": ["位移", "速度", "力", "功"], "answer": 1, "explanation": "∫a(t)dt = v(t)。"},
        {"question": "力的积分等于？", "options": ["质量", "速度", "功", "加速度"], "answer": 2, "explanation": "∫F·ds = W（功）。"},
        {"question": "∫₀¹ 2x dx = ?", "options": ["0", "1", "2", "x²"], "answer": 1, "explanation": "[x²]₀¹ = 1。"},
        {"question": "∫₁² (1/x) dx = ?", "options": ["0", "ln2", "1", "2"], "answer": 1, "explanation": "[ln|x|]₁² = ln2。"},
        {"question": "d/dx ∫₀ˣ t² dt = ?", "options": ["x²", "x³/3", "2x", "0"], "answer": 0, "explanation": "微积分基本定理：f(x)。"},
        {"question": "∫₀¹ eˣ dx = ?", "options": ["0", "1", "e", "e-1"], "answer": 3, "explanation": "[eˣ]₀¹ = e-1。"},
        {"question": "微分和积分是？", "options": ["相同", "互逆", "无关", "相反"], "answer": 1, "explanation": "微分和积分互为逆运算。"},
        {"question": "∫₀π cos(x) dx = ?", "options": ["-2", "0", "1", "2"], "answer": 1, "explanation": "[sin x]₀π = sinπ-sin0 = 0。"},
        {"question": "变上限积分 ∫₀ˣ f(t)dt 是？函数", "options": ["常数", "复合", "隐", "分段"], "answer": 1, "explanation": "变上限积分是关于 x 的函数。"},
        {"question": "微积分基本定理的条件是？", "options": ["f 连续", "f 可导", "f 可积", "以上都对"], "answer": 0, "explanation": "f 在 [a,b] 上连续。"},
    ],
    "t26": [
        {"question": "数列 2,4,6,8,... 的通项是？", "options": ["n", "2n", "n+1", "2n-1"], "answer": 1, "explanation": "aₙ = 2n。"},
        {"question": "数列 1,3,5,7,... 的通项是？", "options": ["n", "2n", "n+1", "2n-1"], "answer": 3, "explanation": "aₙ = 2n-1。"},
        {"question": "数列 1,4,9,16,... 的通项是？", "options": ["n", "2n", "n²", "2n-1"], "answer": 2, "explanation": "aₙ = n²。"},
        {"question": "数列 1,1/2,1/3,1/4,... 的通项是？", "options": ["n", "1/n", "n²", "2n"], "answer": 1, "explanation": "aₙ = 1/n。"},
        {"question": "等差数列 3,7,11,15,... 的公差是？", "options": ["3", "4", "5", "7"], "answer": 1, "explanation": "d = 7-3 = 4。"},
        {"question": "等差数列的通项公式是？", "options": ["a₁+nd", "a₁+(n-1)d", "nd", "a₁d"], "answer": 1, "explanation": "aₙ = a₁ + (n-1)d。"},
        {"question": "等差数列前 n 项和公式是？", "options": ["na₁", "n(a₁+aₙ)/2", "nd", "a₁d"], "answer": 1, "explanation": "Sₙ = n(a₁+aₙ)/2。"},
        {"question": "等比数列 2,6,18,... 的公比是？", "options": ["2", "3", "4", "6"], "answer": 1, "explanation": "q = 6/2 = 3。"},
        {"question": "等比数列的通项公式是？", "options": ["a₁+nd", "a₁qⁿ", "a₁qⁿ⁻¹", "nq"], "answer": 2, "explanation": "aₙ = a₁·qⁿ⁻¹。"},
        {"question": "等比数列前 n 项和公式是？", "options": ["na₁", "a₁(1-qⁿ)/(1-q)", "a₁qⁿ", "nq"], "answer": 1, "explanation": "Sₙ = a₁(1-qⁿ)/(1-q) (q≠1)。"},
        {"question": "1+2+3+...+100 = ?", "options": ["5000", "5050", "5100", "10000"], "answer": 1, "explanation": "S = 100×101/2 = 5050。"},
        {"question": "等差数列中项 aₙ = ?", "options": ["(aₙ₋₁+aₙ₊₁)/2", "aₙ₋₁+aₙ₊₁", "aₙ₋₁×aₙ₊₁", "√(aₙ₋₁×aₙ₊₁)"], "answer": 0, "explanation": "等差中项：aₙ 是前后两项的算术平均。"},
        {"question": "等比数列中项 aₙ = ?", "options": ["(aₙ₋₁+aₙ₊₁)/2", "aₙ₋₁+aₙ₊₁", "aₙ₋₁×aₙ₊₁", "√(aₙ₋₁×aₙ₊₁)"], "answer": 3, "explanation": "等比中项：aₙ 是前后两项的几何平均。"},
        {"question": "斐波那契数列的规律是？", "options": ["等差", "等比", "前两项之和", "前两项之积"], "answer": 2, "explanation": "F(n) = F(n-1) + F(n-2)。"},
        {"question": "数列的极限存在说明？", "options": ["有界", "单调", "收敛", "发散"], "answer": 2, "explanation": "极限存在叫收敛。"},
        {"question": "1+1/2+1/4+1/8+... = ?", "options": ["1", "2", "3", "无穷大"], "answer": 1, "explanation": "等比数列求和：a₁=1, q=1/2, S=1/(1-1/2)=2。"},
        {"question": "数列 1,-1,1,-1,... 收敛吗？", "options": ["收敛到0", "收敛到1", "发散", "不确定"], "answer": 2, "explanation": "极限不存在，发散（振荡）。"},
    ],
    "t27": [
        {"question": "A∩B 的元素属于？", "options": ["A", "B", "A和B", "A或B"], "answer": 2, "explanation": "交集：同时属于 A 和 B。"},
        {"question": "A∪B 的元素属于？", "options": ["A", "B", "A和B", "A或B"], "answer": 3, "explanation": "并集：属于 A 或 B。"},
        {"question": "A-B 的元素属于？", "options": ["A", "B", "A和B", "A但不属于B"], "answer": 3, "explanation": "差集：属于 A 但不属于 B。"},
        {"question": "全集 U 中 A 的补集记作？", "options": ["A'", "A*", "-A", "U-A"], "answer": 0, "explanation": "补集记作 A' 或 Ā。"},
        {"question": "A∪A' = ?", "options": ["A", "A'", "U", "∅"], "answer": 2, "explanation": "集合与补集的并集是全集。"},
        {"question": "A∩A' = ?", "options": ["A", "A'", "U", "∅"], "answer": 3, "explanation": "集合与补集的交集是空集。"},
        {"question": "∅ 的补集是？", "options": ["∅", "U", "A", "不确定"], "answer": 1, "explanation": "空集的补集是全集。"},
        {"question": "A⊆B 且 B⊆A 则？", "options": ["A⊂B", "B⊂A", "A=B", "A∩B=∅"], "answer": 2, "explanation": "互相包含则相等。"},
        {"question": "含有 n 个元素的集合有？个子集", "options": ["n", "2n", "2ⁿ", "n²"], "answer": 2, "explanation": "子集数 = 2ⁿ。"},
        {"question": "{1,2,3} 的真子集有？个", "options": ["3", "6", "7", "8"], "answer": 2, "explanation": "真子集 = 2ⁿ-1 = 7（去掉自身）。"},
        {"question": "德摩根定律：(A∪B)' = ?", "options": ["A'∪B'", "A'∩B'", "A∩B", "(A∩B)'"], "answer": 1, "explanation": "并集的补 = 补集的交。"},
        {"question": "德摩根定律：(A∩B)' = ?", "options": ["A'∪B'", "A'∩B'", "A∪B", "(A∪B)'"], "answer": 0, "explanation": "交集的补 = 补集的并。"},
        {"question": "集合 {x|x²=1} = ?", "options": ["{1}", "{-1}", "{1,-1}", "∅"], "answer": 2, "explanation": "x²=1 的解是 ±1。"},
        {"question": "集合 {x|x>0 且 x<0} = ?", "options": ["{0}", "正数", "负数", "∅"], "answer": 3, "explanation": "没有数既大于 0 又小于 0。"},
        {"question": "有限集是指？", "options": ["元素有限", "元素无限", "空集", "子集有限"], "answer": 0, "explanation": "有限集：元素个数有限。"},
        {"question": "自然数集 N 是？", "options": ["有限集", "无限集", "空集", "不确定"], "answer": 1, "explanation": "自然数有无穷多个。"},
    ],
    "t28": [
        {"question": "P(5,3) = ?", "options": ["10", "20", "60", "120"], "answer": 2, "explanation": "5×4×3 = 60。"},
        {"question": "C(10,2) = ?", "options": ["20", "45", "90", "100"], "answer": 1, "explanation": "10×9/2 = 45。"},
        {"question": "0! = ?", "options": ["0", "1", "无意义", "∞"], "answer": 1, "explanation": "定义 0! = 1。"},
        {"question": "5! = ?", "options": ["25", "60", "100", "120"], "answer": 3, "explanation": "5! = 5×4×3×2×1 = 120。"},
        {"question": "C(n,r) = C(n,?)", "options": ["r", "n-r", "n+r", "r-1"], "answer": 1, "explanation": "C(n,r) = C(n,n-r)。"},
        {"question": "二项式定理 (a+b)² = ?", "options": ["a²+b²", "a²+2ab+b²", "a²-b²", "2a+2b"], "answer": 1, "explanation": "完全平方公式。"},
        {"question": "二项式系数之和 = ?", "options": ["n", "2n", "2ⁿ", "n²"], "answer": 2, "explanation": "ΣC(n,k) = 2ⁿ。"},
        {"question": "从 10 人中选 3 人的组合数是？", "options": ["30", "120", "720", "1000"], "answer": 1, "explanation": "C(10,3) = 120。"},
        {"question": "从 10 人中选 3 人的排列数是？", "options": ["30", "120", "720", "1000"], "answer": 2, "explanation": "P(10,3) = 720。"},
        {"question": "4 个字母的全排列有？种", "options": ["4", "12", "24", "48"], "answer": 2, "explanation": "4! = 24。"},
        {"question": "有重复元素的排列怎么算？", "options": ["n!", "n!/重复!", "n²", "2ⁿ"], "answer": 1, "explanation": "除以重复元素的阶乘。"},
        {"question": "AABBC 的排列数是？", "options": ["10", "20", "30", "60"], "answer": 2, "explanation": "5!/(2!2!1!) = 30。"},
        {"question": "从 5 男 3 女中选 2 男 1 女有？种", "options": ["15", "20", "30", "60"], "answer": 2, "explanation": "C(5,2)×C(3,1) = 10×3 = 30。"},
        {"question": "概率 = 有利结果 / ?", "options": ["总结果", "总人数", "总时间", "总面积"], "answer": 0, "explanation": "P = 有利结果数 / 总结果数。"},
        {"question": "掷骰子点数为偶数的概率是？", "options": ["1/6", "1/3", "1/2", "2/3"], "answer": 2, "explanation": "偶数有 2,4,6 三个，P=3/6=1/2。"},
        {"question": "互斥事件 A∪B 的概率 = ?", "options": ["P(A)+P(B)", "P(A)×P(B)", "P(A)+P(B)-P(AB)", "1"], "answer": 0, "explanation": "互斥事件概率可加。"},
    ],
    "t29": [
        {"question": "等差数列求和用什么方法？", "options": ["倒序相加", "错位相减", "裂项", "数学归纳"], "answer": 0, "explanation": "倒序相加法。"},
        {"question": "等比数列求和用什么方法？", "options": ["倒序相加", "错位相减", "裂项", "数学归纳"], "answer": 1, "explanation": "错位相减法。"},
        {"question": "1+2+3+...+n = ?", "options": ["n²", "n(n+1)/2", "n(n-1)/2", "2n"], "answer": 1, "explanation": "高斯公式。"},
        {"question": "1²+2²+3²+...+n² = ?", "options": ["n(n+1)/2", "n(n+1)(2n+1)/6", "n²(n+1)²/4", "n³"], "answer": 1, "explanation": "平方和公式。"},
        {"question": "1³+2³+3³+...+n³ = ?", "options": ["[n(n+1)/2]²", "n(n+1)(2n+1)/6", "n²(n+1)/2", "n⁴"], "answer": 0, "explanation": "立方和 = 和的平方。"},
        {"question": "裂项求和的关键是？", "options": ["拆成两项之差", "配对", "倒序", "错位"], "answer": 0, "explanation": "裂项：每项拆成两项之差，相邻抵消。"},
        {"question": "1/(1×2) + 1/(2×3) + ... + 1/(n(n+1)) = ?", "options": ["1", "n/(n+1)", "1/(n+1)", "n"], "answer": 1, "explanation": "裂项：1-1/(n+1) = n/(n+1)。"},
        {"question": "数列求和的方法有？", "options": ["公式法", "裂项法", "错位相减", "以上都有"], "answer": 3, "explanation": "多种求和方法。"},
        {"question": "2+4+6+...+2n = ?", "options": ["n(n+1)", "n²", "2n(n+1)", "n(n-1)"], "answer": 0, "explanation": "2(1+2+...+n) = 2×n(n+1)/2 = n(n+1)。"},
        {"question": "1+3+5+...+(2n-1) = ?", "options": ["n", "n²", "n(n+1)", "2n"], "answer": 1, "explanation": "前 n 个奇数之和 = n²。"},
        {"question": "等差数列 Sₙ 是关于 n 的？次函数", "options": ["1", "2", "3", "n"], "answer": 1, "explanation": "Sₙ = na₁+n(n-1)d/2，是 n 的二次函数。"},
        {"question": "等比数列 |q|<1 时，无穷项和 = ?", "options": ["a₁/(1-q)", "a₁q/(1-q)", "无穷大", "0"], "answer": 0, "explanation": "S = a₁/(1-q) (|q|<1)。"},
        {"question": "1+1/2+1/4+...+1/2ⁿ = ?", "options": ["1", "2", "2-1/2ⁿ", "无穷大"], "answer": 2, "explanation": "等比数列部分和。"},
        {"question": "1-1/2+1/3-1/4+... 收敛吗？", "options": ["收敛", "发散", "不确定", "等于0"], "answer": 0, "explanation": "交错调和级数收敛到 ln2。"},
        {"question": "1+1/2+1/3+...+1/n 收敛吗？", "options": ["收敛", "发散", "不确定", "等于1"], "answer": 1, "explanation": "调和级数发散。"},
    ],
    "t30": [
        {"question": "矩阵 A 的转置记作？", "options": ["A'", "Aᵀ", "A*", "A⁻¹"], "answer": 1, "explanation": "转置记作 Aᵀ 或 A'。"},
        {"question": "(Aᵀ)ᵀ = ?", "options": ["A", "Aᵀ", "2A", "0"], "answer": 0, "explanation": "转置的转置等于原矩阵。"},
        {"question": "(AB)ᵀ = ?", "options": ["AᵀBᵀ", "BᵀAᵀ", "AB", "BA"], "answer": 1, "explanation": "(AB)ᵀ = BᵀAᵀ。"},
        {"question": "矩阵加法满足？", "options": ["交换律", "结合律", "交换律和结合律", "分配律"], "answer": 2, "explanation": "矩阵加法满足交换律和结合律。"},
        {"question": "矩阵乘法满足交换律吗？", "options": ["满足", "不满足", "有时满足", "不确定"], "answer": 1, "explanation": "矩阵乘法一般不满足交换律。"},
        {"question": "单位矩阵 I 的特点是？", "options": ["全为0", "对角为1", "全为1", "随机"], "answer": 1, "explanation": "对角线元素为 1，其余为 0。"},
        {"question": "AI = ?", "options": ["A", "I", "0", "A²"], "answer": 0, "explanation": "任何矩阵乘单位矩阵等于自身。"},
        {"question": "矩阵可逆的条件是？", "options": ["det(A)=0", "det(A)≠0", "A=Aᵀ", "A=0"], "answer": 1, "explanation": "行列式不为 0 时可逆。"},
        {"question": "AA⁻¹ = ?", "options": ["A", "A⁻¹", "I", "0"], "answer": 2, "explanation": "矩阵乘其逆等于单位矩阵。"},
        {"question": "2×2 矩阵 [[a,b],[c,d]] 的行列式 = ?", "options": ["ad+bc", "ad-bc", "ab-cd", "ac-bd"], "answer": 1, "explanation": "det = ad-bc。"},
        {"question": "矩阵的秩是？", "options": ["行数", "列数", "非零子式的最高阶数", "元素个数"], "answer": 2, "explanation": "秩 = 非零子式的最高阶数。"},
        {"question": "齐次方程组 Ax=0 有非零解的条件？", "options": ["det(A)=0", "det(A)≠0", "A=I", "A=0"], "answer": 0, "explanation": "det(A)=0 时有非零解。"},
        {"question": "矩阵 [[1,0],[0,1]] 是？", "options": ["零矩阵", "单位矩阵", "对角矩阵", "对称矩阵"], "answer": 1, "explanation": "2×2 单位矩阵。"},
        {"question": "对称矩阵满足？", "options": ["A=Aᵀ", "A=-Aᵀ", "A=A⁻¹", "A=0"], "answer": 0, "explanation": "对称矩阵等于其转置。"},
        {"question": "反对称矩阵满足？", "options": ["A=Aᵀ", "A=-Aᵀ", "A=A⁻¹", "A=0"], "answer": 1, "explanation": "反对称矩阵等于其转置的相反数。"},
    ],
}
