"""
完整题库扩充 第2部分 — 几何、函数、微积分、高等数学
"""

FULL_QUIZ_2 = {
    "t11": [
        {"question": "射线有几个端点？", "options": ["0", "1", "2", "无数"], "answer": 1, "explanation": "射线有一个端点，向一端无限延伸。"},
        {"question": "直线有几个端点？", "options": ["0", "1", "2", "无数"], "answer": 0, "explanation": "直线没有端点，向两端无限延伸。"},
        {"question": "两条直线相交形成？个角", "options": ["2", "3", "4", "6"], "answer": 2, "explanation": "两直线相交形成 4 个角。"},
        {"question": "对顶角？", "options": ["互补", "相等", "互余", "不确定"], "answer": 1, "explanation": "对顶角相等。"},
        {"question": "垂直的符号是？", "options": ["//", "⊥", "∠", "△"], "answer": 1, "explanation": "⊥ 表示垂直，// 表示平行。"},
        {"question": "过直线外一点有几条垂线？", "options": ["0", "1", "2", "无数"], "answer": 1, "explanation": "过直线外一点有且只有一条垂线。"},
        {"question": "点到直线的距离是？", "options": ["任意线段", "垂线段", "斜线段", "水平线段"], "answer": 1, "explanation": "点到直线的距离是垂线段的长度。"},
        {"question": "中点把线段分成？", "options": ["两段不等", "两段相等", "三段", "四段"], "answer": 1, "explanation": "中点平分线段。"},
        {"question": "角的度量单位是？", "options": ["米", "度", "弧度", "以上都有"], "answer": 3, "explanation": "角度用度(°)或弧度(rad)度量。"},
        {"question": "1° = ?'", "options": ["10", "30", "60", "100"], "answer": 2, "explanation": "1° = 60'（角分）。"},
        {"question": "1' = ?''", "options": ["10", "30", "60", "100"], "answer": 2, "explanation": "1' = 60''（角秒）。"},
        {"question": "平角 = ?°", "options": ["90", "180", "270", "360"], "answer": 1, "explanation": "平角 = 180°。"},
        {"question": "周角 = ?°", "options": ["90", "180", "270", "360"], "answer": 3, "explanation": "周角 = 360°。"},
        {"question": "锐角的范围是？", "options": ["0-45°", "0-90°", "90-180°", "180-360°"], "answer": 1, "explanation": "锐角：0° < α < 90°。"},
        {"question": "钝角的范围是？", "options": ["0-90°", "90-180°", "180-270°", "270-360°"], "answer": 1, "explanation": "钝角：90° < α < 180°。"},
        {"question": "余角之和 = ?", "options": ["45°", "90°", "180°", "360°"], "answer": 1, "explanation": "互余两角之和为 90°。"},
        {"question": "补角之和 = ?", "options": ["45°", "90°", "180°", "360°"], "answer": 2, "explanation": "互补两角之和为 180°。"},
    ],
    "t12": [
        {"question": "内错角相等说明两直线？", "options": ["相交", "平行", "垂直", "重合"], "answer": 1, "explanation": "内错角相等 ⇒ 两直线平行。"},
        {"question": "同旁内角互补说明两直线？", "options": ["相交", "平行", "垂直", "重合"], "answer": 1, "explanation": "同旁内角互补 ⇒ 两直线平行。"},
        {"question": "两直线平行，同位角？", "options": ["互补", "相等", "互余", "不确定"], "answer": 1, "explanation": "两直线平行 ⇒ 同位角相等。"},
        {"question": "两直线平行，内错角？", "options": ["互补", "相等", "互余", "不确定"], "answer": 1, "explanation": "两直线平行 ⇒ 内错角相等。"},
        {"question": "两直线平行，同旁内角？", "options": ["互补", "相等", "互余", "不确定"], "answer": 0, "explanation": "两直线平行 ⇒ 同旁内角互补。"},
        {"question": "平行线的传递性是？", "options": ["a//b, b//c ⇒ a//c", "a//b ⇒ b//a", "a⊥b ⇒ b⊥a", "以上都是"], "answer": 0, "explanation": "平行线的传递性。"},
        {"question": "垂直于同一直线的两直线？", "options": ["平行", "相交", "垂直", "不确定"], "answer": 0, "explanation": "垂直于同一直线的两直线平行。"},
        {"question": "三角形外角等于？", "options": ["内角和", "不相邻两内角之和", "相邻内角", "180°"], "answer": 1, "explanation": "三角形外角等于不相邻两内角之和。"},
        {"question": "三角形外角和 = ?", "options": ["180°", "360°", "540°", "720°"], "answer": 1, "explanation": "任意多边形外角和都是 360°。"},
        {"question": "三角形两边之差？第三边", "options": ["大于", "等于", "小于", "不确定"], "answer": 2, "explanation": "|a-b| < c < a+b。"},
        {"question": "等腰三角形两底角？", "options": ["互补", "相等", "互余", "不确定"], "answer": 1, "explanation": "等腰三角形两底角相等。"},
        {"question": "等边三角形每个角？°", "options": ["30", "45", "60", "90"], "answer": 2, "explanation": "180°÷3 = 60°。"},
        {"question": "直角三角形两锐角之和 = ?°", "options": ["45", "60", "90", "180"], "answer": 2, "explanation": "180° - 90° = 90°。"},
        {"question": "30° 角的直角三角形，短边是斜边的？", "options": ["1/2", "1/3", "1/4", "√3/2"], "answer": 0, "explanation": "30° 对边是斜边的一半。"},
        {"question": "三角形的中位线平行于？且等于？", "options": ["第三边，一半", "底边，两倍", "高，一半", "不确定"], "answer": 0, "explanation": "中位线平行于第三边且等于第三边的一半。"},
        {"question": "角平分线上的点到角两边距离？", "options": ["不等", "相等", "成比例", "不确定"], "answer": 1, "explanation": "角平分线性质：到两边距离相等。"},
    ],
    "t13": [
        {"question": "直角三角形面积 = ?", "options": ["ab", "ab/2", "a+b", "c²"], "answer": 1, "explanation": "直角边乘积的一半。"},
        {"question": "勾股定理的逆定理是？", "options": ["a²+b²=c² ⇒ 直角", "直角 ⇒ a²+b²=c²", "a+b>c", "a²+b²>c²"], "answer": 0, "explanation": "如果 a²+b²=c²，则三角形是直角三角形。"},
        {"question": "勾股数 5,12,13 中斜边是？", "options": ["5", "12", "13", "都不是"], "answer": 2, "explanation": "5²+12²=169=13²，斜边是 13。"},
        {"question": "等边三角形面积公式是？", "options": ["a²", "a²√3/4", "a²/2", "3a²"], "answer": 1, "explanation": "S = a²√3/4。"},
        {"question": "三角形的高是从顶点到对边的？", "options": ["中线", "垂线", "角平分线", "平行线"], "answer": 1, "explanation": "高是从顶点到对边的垂线段。"},
        {"question": "三角形的中线连接顶点和对边的？", "options": ["端点", "中点", "垂足", "任意点"], "answer": 1, "explanation": "中线连接顶点和对边中点。"},
        {"question": "三角形三条中线交于一点叫？", "options": ["内心", "外心", "重心", "垂心"], "answer": 2, "explanation": "重心，它到顶点的距离是到对边中点距离的 2 倍。"},
        {"question": "三角形三条高交于一点叫？", "options": ["内心", "外心", "重心", "垂心"], "answer": 3, "explanation": "垂心。"},
        {"question": "三角形内切圆圆心是？", "options": ["内心", "外心", "重心", "垂心"], "answer": 0, "explanation": "内心是三条角平分线的交点。"},
        {"question": "三角形外接圆圆心是？", "options": ["内心", "外心", "重心", "垂心"], "answer": 1, "explanation": "外心是三条垂直平分线的交点。"},
        {"question": "SSS 全等判定是？", "options": ["三边相等", "两边一角", "两角一边", "三角相等"], "answer": 0, "explanation": "三边对应相等的两三角形全等。"},
        {"question": "SAS 全等判定是？", "options": ["三边相等", "两边及夹角", "两角一边", "三角相等"], "answer": 1, "explanation": "两边及夹角对应相等。"},
        {"question": "ASA 全等判定是？", "options": ["三边相等", "两边一角", "两角及夹边", "三角相等"], "answer": 2, "explanation": "两角及夹边对应相等。"},
        {"question": "相似三角形的对应边？", "options": ["相等", "成比例", "平行", "垂直"], "answer": 1, "explanation": "相似三角形对应边成比例。"},
        {"question": "相似三角形面积比 = 边比的？", "options": ["1倍", "2倍", "平方", "立方"], "answer": 2, "explanation": "面积比 = 边比的平方。"},
        {"question": "三角形稳定性是指？", "options": ["形状不变", "大小不变", "角度不变", "位置不变"], "answer": 0, "explanation": "三角形三边确定后形状唯一（稳定性）。"},
    ],
    "t14": [
        {"question": "平行四边形对角线？", "options": ["相等", "垂直", "互相平分", "平分角"], "answer": 2, "explanation": "平行四边形对角线互相平分。"},
        {"question": "菱形的对角线？", "options": ["相等", "垂直", "互相平分", "垂直且平分"], "answer": 3, "explanation": "菱形对角线垂直且互相平分。"},
        {"question": "梯形只有一组对边？", "options": ["相等", "平行", "垂直", "平分"], "answer": 1, "explanation": "梯形只有一组对边平行。"},
        {"question": "等腰梯形的两腰？", "options": ["平行", "相等", "垂直", "平分"], "answer": 1, "explanation": "等腰梯形两腰相等。"},
        {"question": "n 边形内角和 = ?", "options": ["n×180°", "(n-1)×180°", "(n-2)×180°", "(n-3)×180°"], "answer": 2, "explanation": "n 边形内角和 = (n-2)×180°。"},
        {"question": "六边形内角和 = ?°", "options": ["360", "540", "720", "900"], "answer": 2, "explanation": "(6-2)×180° = 720°。"},
        {"question": "正多边形每个内角 = ?", "options": ["180°/n", "360°/n", "(n-2)×180°/n", "n×180°"], "answer": 2, "explanation": "正 n 边形每个内角 = (n-2)×180°/n。"},
        {"question": "正六边形每个内角 = ?°", "options": ["60", "90", "108", "120"], "answer": 3, "explanation": "(6-2)×180°/6 = 120°。"},
        {"question": "平行四边形面积 = ?", "options": ["底×高", "底×高/2", "长×宽", "对角线乘积/2"], "answer": 0, "explanation": "平行四边形面积 = 底 × 高。"},
        {"question": "梯形面积 = ?", "options": ["底×高", "(上底+下底)×高/2", "长×宽", "对角线乘积/2"], "answer": 1, "explanation": "梯形面积 = (上底+下底) × 高 ÷ 2。"},
        {"question": "菱形面积 = ?", "options": ["边长²", "对角线乘积/2", "底×高", "周长×高"], "answer": 1, "explanation": "菱形面积 = 两对角线乘积 ÷ 2。"},
        {"question": "矩形是特殊的？", "options": ["三角形", "平行四边形", "梯形", "菱形"], "answer": 1, "explanation": "矩形是四个角都是直角的平行四边形。"},
        {"question": "正方形是特殊的？", "options": ["矩形", "菱形", "平行四边形", "以上都是"], "answer": 3, "explanation": "正方形同时是矩形、菱形、平行四边形。"},
        {"question": "四边形具有稳定性吗？", "options": ["有", "没有", "有时有", "不确定"], "answer": 1, "explanation": "四边形不具有稳定性（可变形）。"},
        {"question": "正方形对角线互相？", "options": ["垂直", "平分", "垂直且平分", "相等"], "answer": 2, "explanation": "正方形对角线垂直、平分且相等。"},
        {"question": "梯形中位线 = ?", "options": ["上底+下底", "(上底+下底)/2", "上底×下底", "高/2"], "answer": 1, "explanation": "梯形中位线平行于两底且等于两底和的一半。"},
    ],
    "t15": [
        {"question": "圆的对称轴有？条", "options": ["1", "2", "4", "无数"], "answer": 3, "explanation": "圆有无数条对称轴（每条直径）。"},
        {"question": "圆心角定理：圆心角 = ?", "options": ["弧度", "圆周角", "弦切角", "不确定"], "answer": 1, "explanation": "圆心角等于同弧上圆周角的 2 倍。"},
        {"question": "圆周角 = 圆心角的？", "options": ["1/2", "1/3", "2倍", "相等"], "answer": 0, "explanation": "圆周角 = 圆心角 / 2。"},
        {"question": "直径所对的圆周角 = ?°", "options": ["45", "60", "90", "180"], "answer": 2, "explanation": "直径所对的圆周角是直角（90°）。"},
        {"question": "切线与半径的关系是？", "options": ["平行", "垂直", "成 45°", "不确定"], "answer": 1, "explanation": "切线垂直于过切点的半径。"},
        {"question": "切线长定理：从圆外一点引两条切线，它们？", "options": ["平行", "相等", "垂直", "不确定"], "answer": 1, "explanation": "两条切线长相等。"},
        {"question": "弧长公式 l = ?", "options": ["2πr", "πr²", "nπr/180", "nr"], "answer": 2, "explanation": "弧长 l = nπr/180（n 为圆心角度数）。"},
        {"question": "扇形面积 S = ?", "options": ["πr²", "nπr²/360", "lr/2", "以上都对"], "answer": 3, "explanation": "扇形面积 = nπr²/360 = lr/2。"},
        {"question": "圆内接四边形对角？", "options": ["相等", "互补", "垂直", "不确定"], "answer": 1, "explanation": "圆内接四边形对角互补。"},
        {"question": "两圆位置关系有？种", "options": ["3", "4", "5", "6"], "answer": 2, "explanation": "外离、外切、相交、内切、内含。"},
        {"question": "两圆外切时圆心距 = ?", "options": ["r1-r2", "r1+r2", "|r1-r2|", "0"], "answer": 1, "explanation": "外切：d = r1 + r2。"},
        {"question": "两圆内切时圆心距 = ?", "options": ["r1-r2", "r1+r2", "|r1-r2|", "0"], "answer": 2, "explanation": "内切：d = |r1 - r2|。"},
        {"question": "两圆相交时圆心距范围是？", "options": ["d>r1+r2", "d=r1+r2", "|r1-r2|<d<r1+r2", "d<|r1-r2|"], "answer": 2, "explanation": "相交：|r1-r2| < d < r1+r2。"},
        {"question": "圆的面积与半径的关系是？", "options": ["正比", "正比于平方", "反比", "无关"], "answer": 1, "explanation": "S = πr²，面积与半径的平方成正比。"},
        {"question": "同心圆的圆心距 = ?", "options": ["r1+r2", "|r1-r2|", "0", "不确定"], "answer": 2, "explanation": "同心圆圆心重合，距离为 0。"},
        {"question": "圆的周长与直径的比值是？", "options": ["e", "π", "φ", "√2"], "answer": 1, "explanation": "π = C/d ≈ 3.14159。"},
    ],
    "t16": [
        {"question": "f(x) = 2x，f(5) = ?", "options": ["5", "7", "10", "12"], "answer": 2, "explanation": "f(5) = 2×5 = 10。"},
        {"question": "f(x) = x²+1，f(-3) = ?", "options": ["8", "9", "10", "11"], "answer": 2, "explanation": "f(-3) = (-3)²+1 = 9+1 = 10。"},
        {"question": "值域是？", "options": ["所有输入", "所有输出", "定义域", "函数图像"], "answer": 1, "explanation": "值域是函数所有可能的输出值。"},
        {"question": "y = x² 的值域是？", "options": ["全体实数", "y≥0", "y>0", "y≤0"], "answer": 1, "explanation": "x² ≥ 0，所以值域是 y ≥ 0。"},
        {"question": "y = 1/x 的定义域是？", "options": ["x>0", "x<0", "x≠0", "全体实数"], "answer": 2, "explanation": "分母不能为 0。"},
        {"question": "奇函数满足 f(-x) = ?", "options": ["f(x)", "-f(x)", "1/f(x)", "f(1/x)"], "answer": 1, "explanation": "奇函数：f(-x) = -f(x)。"},
        {"question": "偶函数满足 f(-x) = ?", "options": ["f(x)", "-f(x)", "1/f(x)", "f(1/x)"], "answer": 0, "explanation": "偶函数：f(-x) = f(x)。"},
        {"question": "y = x² 是？", "options": ["奇函数", "偶函数", "非奇非偶", "既奇又偶"], "answer": 1, "explanation": "f(-x) = (-x)² = x² = f(x)，偶函数。"},
        {"question": "y = x³ 是？", "options": ["奇函数", "偶函数", "非奇非偶", "既奇又偶"], "answer": 0, "explanation": "f(-x) = (-x)³ = -x³ = -f(x)，奇函数。"},
        {"question": "反函数的图像是关于？对称", "options": ["x轴", "y轴", "原点", "y=x"], "answer": 3, "explanation": "反函数图像与原函数关于 y=x 对称。"},
        {"question": "y = 2x 的反函数是？", "options": ["y=x/2", "y=2/x", "y=-2x", "y=x²"], "answer": 0, "explanation": "交换 x 和 y：x=2y，y=x/2。"},
        {"question": "函数的三要素是？", "options": ["定义域、值域、对应法则", "x、y、f", "输入、输出、过程", "图像、公式、表格"], "answer": 0, "explanation": "三要素：定义域、值域、对应法则。"},
        {"question": "单调递增函数的图像是？", "options": ["上升", "下降", "水平", "波动"], "answer": 0, "explanation": "从左到右上升。"},
        {"question": "单调递减函数的图像是？", "options": ["上升", "下降", "水平", "波动"], "answer": 1, "explanation": "从左到右下降。"},
        {"question": "常数函数的图像是？", "options": ["水平线", "竖直线", "斜线", "曲线"], "answer": 0, "explanation": "y = c 是水平线。"},
        {"question": "分段函数是？", "options": ["多个函数", "一个函数", "不连续函数", "无法定义"], "answer": 1, "explanation": "分段函数是一个函数，只是在不同区间用不同表达式。"},
    ],
    "t17": [
        {"question": "y = kx + b 的图像是？", "options": ["曲线", "直线", "抛物线", "圆"], "answer": 1, "explanation": "一次函数图像是直线。"},
        {"question": "k > 0 时直线？", "options": ["上升", "下降", "水平", "竖直"], "answer": 0, "explanation": "k > 0：从左到右上升。"},
        {"question": "k < 0 时直线？", "options": ["上升", "下降", "水平", "竖直"], "answer": 1, "explanation": "k < 0：从左到右下降。"},
        {"question": "b 的几何意义是？", "options": ["斜率", "与x轴交点", "与y轴交点", "面积"], "answer": 2, "explanation": "b 是直线与 y 轴的交点（截距）。"},
        {"question": "y = 3x - 6 与 y 轴交点是？", "options": ["(0,-6)", "(2,0)", "(-6,0)", "(0,3)"], "answer": 0, "explanation": "x=0 时 y=-6，交点 (0,-6)。"},
        {"question": "两直线平行的条件是？", "options": ["k1=k2", "k1≠k2", "k1×k2=-1", "k1×k2=1"], "answer": 0, "explanation": "平行：斜率相等。"},
        {"question": "两直线垂直的条件是？", "options": ["k1=k2", "k1≠k2", "k1×k2=-1", "k1×k2=1"], "answer": 2, "explanation": "垂直：斜率之积为 -1。"},
        {"question": "y = 2x + 1 过哪个点？", "options": ["(0,0)", "(0,1)", "(1,0)", "(1,1)"], "answer": 1, "explanation": "x=0 时 y=1，过 (0,1)。"},
        {"question": "一次函数过 (1,3) 和 (2,5)，k=?", "options": ["1", "2", "3", "4"], "answer": 1, "explanation": "k = (5-3)/(2-1) = 2。"},
        {"question": "正比例函数是？的特殊一次函数", "options": ["b=0", "k=0", "b=1", "k=1"], "answer": 0, "explanation": "正比例函数 y=kx（b=0）。"},
        {"question": "y = -x 的图像经过？象限", "options": ["1,2", "1,3", "2,4", "3,4"], "answer": 2, "explanation": "k=-1<0，过原点，经过二四象限。"},
        {"question": "一次函数的值域是？", "options": ["y>0", "y<0", "y≥0", "全体实数"], "answer": 3, "explanation": "一次函数可以取任意实数值。"},
        {"question": "两直线 {y=2x+1, y=-x+4} 的交点是？", "options": ["(1,3)", "(3,1)", "(2,5)", "(0,4)"], "answer": 0, "explanation": "2x+1=-x+4，3x=3，x=1，y=3。"},
        {"question": "直线 y=2x+1 与 x 轴交点是？", "options": ["(-1/2, 0)", "(1/2, 0)", "(0, 1)", "(1, 3)"], "answer": 0, "explanation": "y=0 时 2x+1=0，x=-1/2。"},
        {"question": "一次函数的图像可以通过？确定", "options": ["两点", "一点和斜率", "斜率和截距", "以上都对"], "answer": 3, "explanation": "多种方式确定一条直线。"},
    ],
    "t18": [
        {"question": "y = ax² + bx + c 中 a ≠ 0 的原因是？", "options": ["a=0 不是二次", "a=0 图像变了", "a=0 无意义", "以上都对"], "answer": 0, "explanation": "a=0 就变成一次函数了。"},
        {"question": "a > 0 时抛物线开口？", "options": ["向上", "向下", "向左", "向右"], "answer": 0, "explanation": "a > 0 开口向上。"},
        {"question": "a < 0 时抛物线开口？", "options": ["向上", "向下", "向左", "向右"], "answer": 1, "explanation": "a < 0 开口向下。"},
        {"question": "|a| 越大，抛物线越？", "options": ["宽", "窄", "高", "低"], "answer": 1, "explanation": "|a| 越大开口越窄。"},
        {"question": "y = x² 的对称轴是？", "options": ["x轴", "y轴", "原点", "y=x"], "answer": 1, "explanation": "y=x² 的对称轴是 y 轴（x=0）。"},
        {"question": "y = (x-2)² 的对称轴是？", "options": ["x=0", "x=2", "y=0", "y=2"], "answer": 1, "explanation": "对称轴 x=2。"},
        {"question": "y = x² - 4x + 3 的零点是？", "options": ["x=1,3", "x=-1,-3", "x=2,4", "x=-2,-4"], "answer": 0, "explanation": "(x-1)(x-3)=0，x=1 或 x=3。"},
        {"question": "判别式 Δ = 0 时有几个零点？", "options": ["0", "1", "2", "3"], "answer": 1, "explanation": "Δ=0 有一个（重）零点。"},
        {"question": "判别式 Δ < 0 时零点情况？", "options": ["无零点", "一个零点", "两个零点", "不确定"], "answer": 0, "explanation": "Δ<0 无实数零点。"},
        {"question": "y = x² + 1 有零点吗？", "options": ["有", "没有", "一个", "两个"], "answer": 1, "explanation": "Δ = 0-4 = -4 < 0，无零点。"},
        {"question": "二次函数最大值出现在？", "options": ["顶点", "端点", "零点", "任意点"], "answer": 0, "explanation": "顶点是极值点。"},
        {"question": "y = -x² + 4 的最大值是？", "options": ["0", "2", "4", "8"], "answer": 2, "explanation": "顶点 (0,4)，最大值 4。"},
        {"question": "y = (x-1)² + 2 的最小值是？", "options": ["0", "1", "2", "3"], "answer": 2, "explanation": "顶点 (1,2)，最小值 2。"},
        {"question": "二次函数与 x 轴最多有？个交点", "options": ["0", "1", "2", "3"], "answer": 2, "explanation": "最多两个交点（两个零点）。"},
        {"question": "二次函数与 y 轴有？个交点", "options": ["0", "1", "2", "不确定"], "answer": 1, "explanation": "与 y 轴必有一个交点 (0,c)。"},
        {"question": "韦达定理：x₁+x₂ = ?", "options": ["b/a", "-b/a", "c/a", "-c/a"], "answer": 1, "explanation": "x₁+x₂ = -b/a。"},
        {"question": "韦达定理：x₁×x₂ = ?", "options": ["b/a", "-b/a", "c/a", "-c/a"], "answer": 2, "explanation": "x₁×x₂ = c/a。"},
    ],
    "t19": [
        {"question": "2⁴ = ?", "options": ["6", "8", "12", "16"], "answer": 3, "explanation": "2⁴ = 16。"},
        {"question": "3² = ?", "options": ["6", "9", "12", "27"], "answer": 1, "explanation": "3² = 9。"},
        {"question": "a⁰ = ? (a≠0)", "options": ["0", "1", "a", "不确定"], "answer": 1, "explanation": "任何非零数的 0 次方等于 1。"},
        {"question": "a⁻¹ = ?", "options": ["a", "-a", "1/a", "a²"], "answer": 2, "explanation": "a⁻¹ = 1/a。"},
        {"question": "aᵐ × aⁿ = ?", "options": ["aᵐ⁺ⁿ", "aᵐ⁻ⁿ", "aᵐⁿ", "ᵐⁿ√a"], "answer": 0, "explanation": "同底数幂相乘，指数相加。"},
        {"question": "aᵐ ÷ aⁿ = ?", "options": ["aᵐ⁺ⁿ", "aᵐ⁻ⁿ", "aᵐⁿ", "ᵐⁿ√a"], "answer": 1, "explanation": "同底数幂相除，指数相减。"},
        {"question": "(aᵐ)ⁿ = ?", "options": ["aᵐ⁺ⁿ", "aᵐ⁻ⁿ", "aᵐⁿ", "ᵐⁿ√a"], "answer": 2, "explanation": "幂的幂，指数相乘。"},
        {"question": "log₁₀(1000) = ?", "options": ["1", "2", "3", "4"], "answer": 2, "explanation": "10³=1000，所以 log₁₀(1000)=3。"},
        {"question": "log₂(64) = ?", "options": ["4", "5", "6", "7"], "answer": 2, "explanation": "2⁶=64，所以 log₂(64)=6。"},
        {"question": "ln(1) = ?", "options": ["0", "1", "e", "无法确定"], "answer": 0, "explanation": "ln(1) = 0，因为 e⁰ = 1。"},
        {"question": "log_a(a) = ?", "options": ["0", "1", "a", "无法确定"], "answer": 1, "explanation": "log_a(a) = 1，因为 a¹ = a。"},
        {"question": "e ≈ ?", "options": ["2.718", "3.14", "1.618", "2.236"], "answer": 0, "explanation": "e ≈ 2.71828。"},
        {"question": "指数函数 y=2ˣ 过哪个点？", "options": ["(0,0)", "(0,1)", "(1,0)", "(1,1)"], "answer": 1, "explanation": "2⁰ = 1，过 (0,1)。"},
        {"question": "对数函数 y=log₂(x) 过哪个点？", "options": ["(0,0)", "(0,1)", "(1,0)", "(1,1)"], "answer": 2, "explanation": "log₂(1) = 0，过 (1,0)。"},
        {"question": "指数函数和对数函数是？", "options": ["相同", "互逆", "无关", "相反"], "answer": 1, "explanation": "它们互为反函数。"},
        {"question": "y = eˣ 的导数是？", "options": ["eˣ", "xeˣ⁻¹", "1", "ln(x)"], "answer": 0, "explanation": "自然指数函数的导数等于自身。"},
        {"question": "复利公式 A = ?", "options": ["P(1+r)ⁿ", "P+nr", "P×r×n", "P/(1+r)ⁿ"], "answer": 0, "explanation": "复利公式 A = P(1+r)ⁿ。"},
    ],
    "t20": [
        {"question": "sin(30°) = ?", "options": ["0", "1/2", "√2/2", "√3/2"], "answer": 1, "explanation": "sin(30°) = 1/2。"},
        {"question": "cos(60°) = ?", "options": ["0", "1/2", "√2/2", "√3/2"], "answer": 1, "explanation": "cos(60°) = 1/2。"},
        {"question": "sin(45°) = ?", "options": ["0", "1/2", "√2/2", "√3/2"], "answer": 2, "explanation": "sin(45°) = √2/2。"},
        {"question": "cos(0°) = ?", "options": ["0", "1/2", "1", "√3/2"], "answer": 2, "explanation": "cos(0°) = 1。"},
        {"question": "sin(90°) = ?", "options": ["0", "1/2", "1", "√3/2"], "answer": 2, "explanation": "sin(90°) = 1。"},
        {"question": "sin²θ + cos²θ = ?", "options": ["0", "1", "2", "sin2θ"], "answer": 1, "explanation": "勾股恒等式。"},
        {"question": "tan(0°) = ?", "options": ["0", "1", "√3", "不存在"], "answer": 0, "explanation": "tan(0°) = sin0°/cos0° = 0/1 = 0。"},
        {"question": "tan(90°) = ?", "options": ["0", "1", "√3", "不存在"], "answer": 3, "explanation": "cos90°=0，分母为 0，不存在。"},
        {"question": "sin(-θ) = ?", "options": ["sinθ", "-sinθ", "cosθ", "-cosθ"], "answer": 1, "explanation": "正弦是奇函数。"},
        {"question": "cos(-θ) = ?", "options": ["cosθ", "-cosθ", "sinθ", "-sinθ"], "answer": 0, "explanation": "余弦是偶函数。"},
        {"question": "sin(π) = ?", "options": ["0", "1", "-1", "√2/2"], "answer": 0, "explanation": "sin(180°) = 0。"},
        {"question": "cos(π) = ?", "options": ["0", "1", "-1", "√2/2"], "answer": 2, "explanation": "cos(180°) = -1。"},
        {"question": "三角函数的周期是？", "options": ["π", "2π", "π/2", "4π"], "answer": 1, "explanation": "sin 和 cos 的周期是 2π。"},
        {"question": "y = sin(x) 的值域是？", "options": ["[0,1]", "[-1,1]", "[-2,2]", "全体实数"], "answer": 1, "explanation": "sin 值域 [-1,1]。"},
        {"question": "y = 3sin(x) 的振幅是？", "options": ["1", "2", "3", "6"], "answer": 2, "explanation": "振幅 A=3。"},
        {"question": "y = sin(2x) 的周期是？", "options": ["π/2", "π", "2π", "4π"], "answer": 1, "explanation": "周期 = 2π/2 = π。"},
        {"question": "正弦定理：a/sinA = ?", "options": ["b/sinB", "2R", "c/sinC", "以上都对"], "answer": 3, "explanation": "a/sinA = b/sinB = c/sinC = 2R。"},
        {"question": "余弦定理：c² = ?", "options": ["a²+b²", "a²+b²-2abcosC", "a²-b²", "2abcosC"], "answer": 1, "explanation": "c² = a²+b²-2abcosC。"},
    ],
}
