"""
完整题库扩充 — 每个主题 20 道测验题
55 主题 × 20 题 = 1100 道题
"""

FULL_QUIZ = {
    "t1": [
        {"question": "自然数的集合记作？", "options": ["Z", "N", "Q", "R"], "answer": 1, "explanation": "N = {0,1,2,3,...} 表示自然数集。"},
        {"question": "10 进制中，123 的百位是？", "options": ["1", "2", "3", "123"], "answer": 0, "explanation": "百位是最高位 1，表示 1×100。"},
        {"question": "二进制 1101 等于十进制？", "options": ["11", "13", "14", "15"], "answer": 1, "explanation": "1×8+1×4+0×2+1×1 = 13。"},
        {"question": "十六进制用几个符号？", "options": ["8", "10", "16", "2"], "answer": 2, "explanation": "十六进制用 0-9 和 A-F 共 16 个符号。"},
        {"question": "计数的本质是？", "options": ["加法", "一一对应", "乘法", "比较"], "answer": 1, "explanation": "计数就是把物体和自然数建立一一对应。"},
        {"question": "0 的作用是？", "options": ["表示没有", "占位", "起点", "以上都是"], "answer": 3, "explanation": "0 既表示没有，也用于占位（如 105），也是自然数起点。"},
        {"question": "1000 里有几个十？", "options": ["10", "100", "1000", "10000"], "answer": 1, "explanation": "1000 ÷ 10 = 100。"},
        {"question": "罗马数字 X 表示？", "options": ["5", "10", "50", "100"], "answer": 1, "explanation": "罗马数字：V=5, X=10, L=50, C=100。"},
        {"question": "数数时不能？", "options": ["跳数", "重复数", "倒着数", "用手指"], "answer": 1, "explanation": "一一对应要求每个物体只数一次。"},
        {"question": "最小的自然数是？", "options": ["1", "0", "-1", "不存在"], "answer": 1, "explanation": "现代数学定义自然数从 0 开始。"},
        {"question": "十进制的基数是？", "options": ["0", "1", "9", "10"], "answer": 3, "explanation": "十进制逢十进一，基数是 10。"},
        {"question": "10² = ?", "options": ["20", "100", "1000", "200"], "answer": 1, "explanation": "10² = 10×10 = 100。"},
        {"question": "二进制 1000 等于十进制？", "options": ["4", "6", "8", "16"], "answer": 2, "explanation": "1×2³ = 8。"},
        {"question": "位值制的优点是？", "options": ["简单", "用少量符号表示大数", "好看", "历史悠久"], "answer": 1, "explanation": "位值制用 0-9 十个符号就能表示任意大的数。"},
        {"question": "10000 里有几个百？", "options": ["10", "100", "1000", "10000"], "answer": 1, "explanation": "10000 ÷ 100 = 100。"},
        {"question": "一打等于几个？", "options": ["6", "10", "12", "24"], "answer": 2, "explanation": "一打(dozen) = 12 个。"},
        {"question": "计算机用什么进制？", "options": ["十进制", "二进制", "八进制", "十六进制"], "answer": 1, "explanation": "计算机内部用二进制（0 和 1）表示一切。"},
    ],
    "t2": [
        {"question": "0 + 5 = ?", "options": ["0", "5", "10", "无法计算"], "answer": 1, "explanation": "任何数加 0 等于它本身（加法单位元）。"},
        {"question": "1 × 99 = ?", "options": ["1", "99", "100", "0"], "answer": 1, "explanation": "任何数乘 1 等于它本身（乘法单位元）。"},
        {"question": "0 × 999 = ?", "options": ["0", "999", "1", "无法计算"], "answer": 0, "explanation": "任何数乘 0 等于 0。"},
        {"question": "8 × 125 = ?", "options": ["100", "500", "1000", "1250"], "answer": 2, "explanation": "8×125 = 1000，常用心算组合。"},
        {"question": "25 × 4 = ?", "options": ["75", "90", "100", "120"], "answer": 2, "explanation": "25×4 = 100。"},
        {"question": "加法的逆运算是？", "options": ["乘法", "减法", "除法", "幂"], "answer": 1, "explanation": "减法是加法的逆运算。"},
        {"question": "乘法的逆运算是？", "options": ["加法", "减法", "除法", "幂"], "answer": 2, "explanation": "除法是乘法的逆运算。"},
        {"question": "9 × 9 = ?", "options": ["18", "72", "81", "99"], "answer": 2, "explanation": "9×9 = 81。"},
        {"question": "5 × 5 × 5 = ?", "options": ["15", "25", "75", "125"], "answer": 3, "explanation": "5³ = 125。"},
        {"question": "分配律用字母表示是？", "options": ["a+b=b+a", "a(b+c)=ab+ac", "(ab)c=a(bc)", "a+0=a"], "answer": 1, "explanation": "分配律：a(b+c) = ab + ac。"},
        {"question": "结合律用字母表示是？", "options": ["a+b=b+a", "a(b+c)=ab+ac", "(a+b)+c=a+(b+c)", "a+0=a"], "answer": 2, "explanation": "结合律：(a+b)+c = a+(b+c)。"},
        {"question": "交换律用字母表示是？", "options": ["a+b=b+a", "a(b+c)=ab+ac", "(ab)c=a(bc)", "a+0=a"], "answer": 0, "explanation": "交换律：a+b = b+a。"},
        {"question": "速算 99×7 = ?", "options": ["693", "700", "703", "723"], "answer": 0, "explanation": "99×7 = (100-1)×7 = 700-7 = 693。"},
        {"question": "速算 25×8 = ?", "options": ["150", "175", "200", "250"], "answer": 2, "explanation": "25×8 = 25×4×2 = 100×2 = 200。"},
        {"question": "速算 125×8 = ?", "options": ["800", "900", "1000", "1250"], "answer": 2, "explanation": "125×8 = 1000。"},
        {"question": "连加 1+2+3+4+5 = ?", "options": ["10", "12", "15", "20"], "answer": 2, "explanation": "1+2+3+4+5 = 15。"},
        {"question": "乘法是加法的？", "options": ["逆运算", "简写", "相反", "基础"], "answer": 1, "explanation": "乘法是重复加法的简写。"},
    ],
    "t3": [
        {"question": "5 - 0 = ?", "options": ["0", "5", "10", "无法计算"], "answer": 1, "explanation": "任何数减 0 等于它本身。"},
        {"question": "0 - 5 = ?", "options": ["0", "5", "-5", "无法计算"], "answer": 2, "explanation": "0-5 = -5，引入负数。"},
        {"question": "8 ÷ 1 = ?", "options": ["0", "1", "8", "无法计算"], "answer": 2, "explanation": "任何数除以 1 等于它本身。"},
        {"question": "有余数除法 17 ÷ 5 = ?", "options": ["3 余 1", "3 余 2", "3 余 3", "4 余 1"], "answer": 1, "explanation": "17 = 5×3 + 2，商 3 余 2。"},
        {"question": "被除数 = 除数 × 商 + ?", "options": ["除数", "商", "余数", "被除数"], "answer": 2, "explanation": "被除数 = 除数 × 商 + 余数。"},
        {"question": "余数必须？除数", "options": ["大于", "等于", "小于", "大于等于"], "answer": 2, "explanation": "余数必须小于除数。"},
        {"question": "100 ÷ 7 的余数是？", "options": ["1", "2", "3", "4"], "answer": 1, "explanation": "100 = 7×14 + 2，余数是 2。"},
        {"question": "连续减法等价于？", "options": ["加法", "乘法", "除法", "幂"], "answer": 2, "explanation": "连续减同数等价于除法。"},
        {"question": "减法满足交换律吗？", "options": ["满足", "不满足", "有时满足", "不确定"], "answer": 1, "explanation": "3-5 ≠ 5-3，减法不满足交换律。"},
        {"question": "除法满足交换律吗？", "options": ["满足", "不满足", "有时满足", "不确定"], "answer": 1, "explanation": "6÷2 ≠ 2÷6，除法不满足交换律。"},
        {"question": "12 ÷ 4 × 4 = ?", "options": ["1", "4", "12", "48"], "answer": 2, "explanation": "12÷4=3，3×4=12，还原了。"},
        {"question": "除以一个数等于乘以它的？", "options": ["相反数", "倒数", "绝对值", "平方"], "answer": 1, "explanation": "a÷b = a×(1/b)。"},
        {"question": "20 ÷ 0.5 = ?", "options": ["10", "20", "40", "100"], "answer": 2, "explanation": "除以 0.5 等于乘以 2，20×2 = 40。"},
        {"question": "差 + 减数 = ?", "options": ["差", "减数", "被减数", "0"], "answer": 2, "explanation": "减法验算：差 + 减数 = 被减数。"},
        {"question": "商 × 除数 = ?", "options": ["商", "除数", "被除数", "余数"], "answer": 2, "explanation": "除法验算：商 × 除数 = 被除数（无余数时）。"},
        {"question": "1 ÷ 3 = ?", "options": ["0.3", "0.33...", "0.333...", "1/3"], "answer": 3, "explanation": "1÷3 = 1/3 = 0.333...（无限循环）。"},
        {"question": "减法的逆运算是？", "options": ["减法", "加法", "乘法", "除法"], "answer": 1, "explanation": "加法是减法的逆运算。"},
    ],
    "t4": [
        {"question": "分子为 0 的分数等于？", "options": ["0", "1", "无意义", "无穷大"], "answer": 0, "explanation": "0/b = 0（b≠0）。"},
        {"question": "分母为 0 的分数？", "options": ["等于 0", "等于 1", "无意义", "无穷大"], "answer": 2, "explanation": "分母不能为 0，否则无意义。"},
        {"question": "真分数的分子？分母", "options": ["大于", "等于", "小于", "大于等于"], "answer": 2, "explanation": "真分数：分子 < 分母，值 < 1。"},
        {"question": "假分数的分子？分母", "options": ["大于", "等于", "大于等于", "小于"], "answer": 2, "explanation": "假分数：分子 ≥ 分母，值 ≥ 1。"},
        {"question": "1/2 + 1/2 = ?", "options": ["1/4", "2/4", "1", "2"], "answer": 2, "explanation": "1/2 + 1/2 = 2/2 = 1。"},
        {"question": "3/4 - 1/4 = ?", "options": ["1/2", "2/4", "1/4", "4/4"], "answer": 0, "explanation": "3/4 - 1/4 = 2/4 = 1/2。"},
        {"question": "2/3 × 3/4 = ?", "options": ["6/12", "1/2", "5/7", "8/9"], "answer": 1, "explanation": "2/3 × 3/4 = 6/12 = 1/2。"},
        {"question": "1/2 ÷ 1/4 = ?", "options": ["1/8", "1/2", "2", "4"], "answer": 2, "explanation": "1/2 ÷ 1/4 = 1/2 × 4 = 2。"},
        {"question": "带分数 2又1/3 化成假分数是？", "options": ["7/3", "6/3", "5/3", "8/3"], "answer": 0, "explanation": "2又1/3 = (2×3+1)/3 = 7/3。"},
        {"question": "分数的基本性质是？", "options": ["分子分母同乘同除", "只能乘", "只能除", "不变"], "answer": 0, "explanation": "分子分母同乘或同除一个非零数，分数值不变。"},
        {"question": "通分的目的是？", "options": ["化简", "统一分母", "约分", "比较"], "answer": 1, "explanation": "通分是为了统一分母，方便加减。"},
        {"question": "约分的目的是？", "options": ["统一分母", "化简分数", "比较大小", "通分"], "answer": 1, "explanation": "约分是化简分数，使分子分母互质。"},
        {"question": "最简分数的分子分母？", "options": ["相等", "互质", "都是质数", "都是偶数"], "answer": 1, "explanation": "最简分数的分子分母最大公因数为 1（互质）。"},
        {"question": "5/6 和 7/8 谁大？", "options": ["5/6", "7/8", "一样大", "不确定"], "answer": 1, "explanation": "通分：5/6=20/24，7/8=21/24，7/8 更大。"},
        {"question": "1/3 + 1/6 = ?", "options": ["2/9", "1/2", "2/6", "3/9"], "answer": 1, "explanation": "1/3=2/6，2/6+1/6=3/6=1/2。"},
        {"question": "分数除法的口诀是？", "options": ["直接除", "乘以倒数", "加减", "交叉相乘"], "answer": 1, "explanation": "除以一个分数等于乘以它的倒数。"},
        {"question": "2/5 的倒数是？", "options": ["2/5", "5/2", "10", "1"], "answer": 1, "explanation": "倒数是分子分母互换：5/2。"},
    ],
    "t5": [
        {"question": "0.5 + 0.3 = ?", "options": ["0.8", "0.15", "0.53", "0.58"], "answer": 0, "explanation": "小数加法：0.5+0.3 = 0.8。"},
        {"question": "0.25 = ?", "options": ["1/2", "1/4", "1/5", "1/8"], "answer": 1, "explanation": "0.25 = 25/100 = 1/4。"},
        {"question": "25% = ?", "options": ["0.2", "0.25", "0.5", "2.5"], "answer": 1, "explanation": "25% = 25/100 = 0.25。"},
        {"question": "八折等于？", "options": ["8%", "80%", "0.08", "8.0"], "answer": 1, "explanation": "八折 = 80% = 0.8。"},
        {"question": "原价 200 打九折是？", "options": ["18", "160", "180", "200"], "answer": 2, "explanation": "200 × 90% = 200 × 0.9 = 180。"},
        {"question": "涨了 20% 后是 120，原价是？", "options": ["96", "100", "110", "144"], "answer": 1, "explanation": "设原价 x，x×1.2=120，x=100。"},
        {"question": "0.125 = ?", "options": ["1/4", "1/6", "1/8", "1/10"], "answer": 2, "explanation": "0.125 = 125/1000 = 1/8。"},
        {"question": "循环小数 0.333... = ?", "options": ["1/3", "3/10", "33/100", "1/4"], "answer": 0, "explanation": "0.333... = 1/3。"},
        {"question": "百分数的分母是？", "options": ["10", "100", "1000", "任意"], "answer": 1, "explanation": "百分数以 100 为分母。"},
        {"question": "成数 七成 = ?", "options": ["7%", "17%", "70%", "700%"], "answer": 2, "explanation": "七成 = 70%。"},
        {"question": "折扣 打七五折 = ?", "options": ["25%", "50%", "75%", "125%"], "answer": 2, "explanation": "七五折 = 75% = 0.75。"},
        {"question": "利率 5%，本金 1000，一年利息？", "options": ["5", "50", "100", "500"], "answer": 1, "explanation": "利息 = 本金 × 利率 = 1000 × 5% = 50。"},
        {"question": "税率 20%，收入 5000，交税？", "options": ["100", "500", "1000", "4000"], "answer": 2, "explanation": "税 = 5000 × 20% = 1000。"},
        {"question": "0.999... = ?", "options": ["0.9", "0.99", "1", "无穷大"], "answer": 2, "explanation": "数学证明 0.999... = 1。"},
        {"question": "小数点右移一位，数？", "options": ["不变", "扩大10倍", "缩小10倍", "扩大100倍"], "answer": 1, "explanation": "小数点右移一位 = ×10。"},
        {"question": "小数点左移一位，数？", "options": ["不变", "扩大10倍", "缩小10倍", "缩小100倍"], "answer": 2, "explanation": "小数点左移一位 = ÷10。"},
        {"question": "保留两位小数 3.14159 ≈ ?", "options": ["3.1", "3.14", "3.15", "3.142"], "answer": 1, "explanation": "第三位是 1 < 5，舍去，3.14。"},
    ],
    "t6": [
        {"question": "数轴上原点右边是？", "options": ["负数", "正数", "零", "分数"], "answer": 1, "explanation": "数轴右边是正数，左边是负数。"},
        {"question": "-2 + 5 = ?", "options": ["-7", "-3", "3", "7"], "answer": 2, "explanation": "-2+5 = 3。"},
        {"question": "3 + (-7) = ?", "options": ["-10", "-4", "4", "10"], "answer": 1, "explanation": "3+(-7) = 3-7 = -4。"},
        {"question": "-3 × (-4) = ?", "options": ["-12", "-7", "7", "12"], "answer": 3, "explanation": "负负得正：-3×(-4) = 12。"},
        {"question": "-3 × 4 = ?", "options": ["-12", "-7", "7", "12"], "answer": 0, "explanation": "负正得负：-3×4 = -12。"},
        {"question": "|-8| = ?", "options": ["-8", "8", "0", "16"], "answer": 1, "explanation": "绝对值是距离，|-8| = 8。"},
        {"question": "|0| = ?", "options": ["0", "1", "-1", "无意义"], "answer": 0, "explanation": "0 到原点距离是 0。"},
        {"question": "-1, 0, 1 中最小的是？", "options": ["-1", "0", "1", "一样大"], "answer": 0, "explanation": "-1 < 0 < 1。"},
        {"question": "负数的作用是？", "options": ["表示欠债", "表示零下", "表示相反", "以上都是"], "answer": 3, "explanation": "负数表示相反意义的量。"},
        {"question": "相反数之和等于？", "options": ["-1", "0", "1", "不确定"], "answer": 1, "explanation": "a + (-a) = 0。"},
        {"question": "-(-(-3)) = ?", "options": ["-3", "3", "0", "9"], "answer": 0, "explanation": "负负得正再得负：-3。"},
        {"question": "-1 的倒数是？", "options": ["1", "-1", "0", "不存在"], "answer": 1, "explanation": "-1 × (-1) = 1，所以 -1 的倒数是 -1。"},
        {"question": "温度从 -5° 升到 3°，升了？", "options": ["2°", "8°", "15°", "-2°"], "answer": 1, "explanation": "3-(-5) = 3+5 = 8°。"},
        {"question": "海拔 -155 米表示？", "options": ["高于海平面155米", "低于海平面155米", "海平面下155厘米", "155米"], "answer": 1, "explanation": "负海拔表示低于海平面。"},
        {"question": "数轴上两点距离 = ?", "options": ["a+b", "a-b", "|a-b|", "ab"], "answer": 2, "explanation": "距离 = |a-b|。"},
        {"question": "-2² = ?", "options": ["-4", "4", "-2", "2"], "answer": 0, "explanation": "-2² = -(2²) = -4。注意：(-2)² = 4。"},
        {"question": "(-2)² = ?", "options": ["-4", "4", "-2", "2"], "answer": 1, "explanation": "(-2)² = (-2)×(-2) = 4。"},
    ],
    "t7": [
        {"question": "代数式 3a+2b 中有几项？", "options": ["1", "2", "3", "5"], "answer": 1, "explanation": "两项：3a 和 2b。"},
        {"question": "同类项的什么相同？", "options": ["系数", "字母", "次数", "符号"], "answer": 1, "explanation": "同类项：字母部分完全相同。"},
        {"question": "5x² 和 3x² 是？", "options": ["同类项", "不同类项", "无法合并", "相等"], "answer": 0, "explanation": "字母部分都是 x²，是同类项。"},
        {"question": "5x² 和 5x 是？", "options": ["同类项", "不同类项", "相等", "无法确定"], "answer": 1, "explanation": "x² 和 x 次数不同，不是同类项。"},
        {"question": "去括号：-(a-b) = ?", "options": ["-a-b", "-a+b", "a-b", "a+b"], "answer": 1, "explanation": "括号前是负号，去括号各项变号。"},
        {"question": "化简 2(x+3) = ?", "options": ["2x+3", "2x+6", "x+6", "2x+5"], "answer": 1, "explanation": "分配律：2×x + 2×3 = 2x+6。"},
        {"question": "多项式 2x²+3x-1 的最高次项是？", "options": ["2x²", "3x", "-1", "2x"], "answer": 0, "explanation": "最高次项是 2x²（二次项）。"},
        {"question": "单项式 -5xy 的系数是？", "options": ["5", "-5", "x", "y"], "answer": 1, "explanation": "系数是数字部分 -5。"},
        {"question": "3x²y 的次数是？", "options": ["2", "3", "5", "6"], "answer": 1, "explanation": "次数 = x指数 + y指数 = 2+1 = 3。"},
        {"question": "整式包括？", "options": ["单项式", "多项式", "单项式和多项式", "分数"], "answer": 2, "explanation": "整式 = 单项式 + 多项式。"},
        {"question": "化简 (x+2)(x-2) = ?", "options": ["x²-4", "x²+4", "x²-2", "x²-4x+4"], "answer": 0, "explanation": "平方差公式：(a+b)(a-b) = a²-b²。"},
        {"question": "(a+b)² = ?", "options": ["a²+b²", "a²+2ab+b²", "a²-b²", "2a+2b"], "answer": 1, "explanation": "完全平方公式。"},
        {"question": "(a-b)² = ?", "options": ["a²-b²", "a²-2ab+b²", "a²+2ab+b²", "a²+b²"], "answer": 1, "explanation": "完全平方公式。"},
        {"question": "化简 x²-4x+4 = ?", "options": ["(x-2)²", "(x+2)²", "(x-4)²", "x(x-4)+4"], "answer": 0, "explanation": "完全平方公式反用。"},
        {"question": "3a + 5a = ?", "options": ["8a", "8a²", "15a", "15a²"], "answer": 0, "explanation": "同类项合并：系数相加。"},
        {"question": "2x × 3x = ?", "options": ["5x", "6x", "5x²", "6x²"], "answer": 3, "explanation": "系数相乘，字母相乘：6x²。"},
        {"question": "x³ ÷ x = ?", "options": ["x", "x²", "x³", "x⁴"], "answer": 1, "explanation": "同底数幂相除：指数相减。"},
    ],
    "t8": [
        {"question": "x + 3 = 3 + x 说明等式？", "options": ["对称性", "传递性", "自反性", "交换律"], "answer": 0, "explanation": "等式的对称性。"},
        {"question": "如果 a=b, b=c，则 a=c，这是？", "options": ["对称性", "传递性", "自反性", "交换律"], "answer": 1, "explanation": "等式的传递性。"},
        {"question": "2x = 10 的解是？", "options": ["2", "5", "8", "12"], "answer": 1, "explanation": "x = 10÷2 = 5。"},
        {"question": "x/3 = 6 的解是？", "options": ["2", "9", "18", "3"], "answer": 2, "explanation": "x = 6×3 = 18。"},
        {"question": "3x + 6 = 0 的解是？", "options": ["-6", "-2", "2", "6"], "answer": 1, "explanation": "3x = -6，x = -2。"},
        {"question": "2(x+1) = 10 的解是？", "options": ["3", "4", "5", "6"], "answer": 1, "explanation": "x+1 = 5，x = 4。"},
        {"question": "x - 5 = 3x + 1 的解是？", "options": ["-3", "-2", "2", "3"], "answer": 0, "explanation": "x-3x = 1+5，-2x = 6，x = -3。"},
        {"question": "方程的解是？", "options": ["未知数", "使等式成立的值", "任意数", "常数"], "answer": 1, "explanation": "解是使方程成立的未知数的值。"},
        {"question": "一元一次方程的元指？", "options": ["次数", "未知数个数", "系数", "常数"], "answer": 1, "explanation": "元 = 未知数个数，一元 = 一个未知数。"},
        {"question": "一元一次方程的次指？", "options": ["未知数个数", "最高次数", "项数", "系数"], "answer": 1, "explanation": "次 = 最高次数，一次 = 最高次数为 1。"},
        {"question": "验算方程的解的方法是？", "options": ["代入原方程", "看是否为正数", "计算", "猜"], "answer": 0, "explanation": "把解代入原方程，看左右是否相等。"},
        {"question": "0.5x = 3 的解是？", "options": ["1.5", "3", "6", "15"], "answer": 2, "explanation": "x = 3÷0.5 = 6。"},
        {"question": "x/2 + x/3 = 5 的解是？", "options": ["3", "4", "5", "6"], "answer": 3, "explanation": "通分：5x/6 = 5，x = 6。"},
        {"question": "|x| = 3 的解是？", "options": ["x=3", "x=-3", "x=±3", "无解"], "answer": 2, "explanation": "绝对值方程有两个解。"},
        {"question": "方程 2x+3=2x+5 有解吗？", "options": ["有", "无解", "无穷多解", "不确定"], "answer": 1, "explanation": "化简得 3=5，矛盾，无解。"},
        {"question": "方程 0x=0 有解吗？", "options": ["有唯一解", "无解", "无穷多解", "不确定"], "answer": 2, "explanation": "任何 x 都满足，无穷多解。"},
        {"question": "列方程的关键是？", "options": ["找等量关系", "设未知数", "计算", "验算"], "answer": 0, "explanation": "列方程的核心是找到等量关系。"},
    ],
    "t9": [
        {"question": "x > 3 表示？", "options": ["x 大于 3", "x 大于等于 3", "x 小于 3", "x 等于 3"], "answer": 0, "explanation": "> 表示严格大于。"},
        {"question": "x ≥ 3 表示？", "options": ["x 大于 3", "x 大于等于 3", "x 小于 3", "x 等于 3"], "answer": 1, "explanation": "≥ 表示大于或等于。"},
        {"question": "2x > 6 的解集是？", "options": ["x > 2", "x > 3", "x > 6", "x > 12"], "answer": 1, "explanation": "两边除以 2：x > 3。"},
        {"question": "-x > 3 的解集是？", "options": ["x > -3", "x < -3", "x > 3", "x < 3"], "answer": 1, "explanation": "除以 -1 变号：x < -3。"},
        {"question": "不等式组 {x>1, x<5} 的解集是？", "options": ["x > 1", "x < 5", "1 < x < 5", "无解"], "answer": 2, "explanation": "取交集：1 < x < 5。"},
        {"question": "不等式组 {x<1, x>5} 的解集是？", "options": ["x < 1", "x > 5", "1 < x < 5", "无解"], "answer": 3, "explanation": "无交集，无解。"},
        {"question": "|x| > 2 的解集是？", "options": ["x > 2", "x < -2", "x > 2 或 x < -2", "-2 < x < 2"], "answer": 2, "explanation": "绝对值大于表示距离大于 2。"},
        {"question": "|x| < 2 的解集是？", "options": ["x > 2", "x < -2", "x > 2 或 x < -2", "-2 < x < 2"], "answer": 3, "explanation": "绝对值小于表示距离小于 2。"},
        {"question": "3x - 1 ≤ 5 的解集是？", "options": ["x ≤ 2", "x ≤ 3", "x ≤ 4", "x ≤ 6"], "answer": 0, "explanation": "3x ≤ 6，x ≤ 2。"},
        {"question": "不等式两边乘以负数要？", "options": ["不变号", "变号", "加 1", "减 1"], "answer": 1, "explanation": "乘以负数，不等号方向反转。"},
        {"question": "x² > 0 的解集是？", "options": ["x > 0", "x < 0", "x ≠ 0", "全体实数"], "answer": 2, "explanation": "x² > 0 当且仅当 x ≠ 0。"},
        {"question": "2x + 1 > 0 的解集是？", "options": ["x > -1/2", "x > 1/2", "x > 0", "x > -1"], "answer": 0, "explanation": "2x > -1，x > -1/2。"},
        {"question": "不等式的解集在数轴上用？表示", "options": ["点", "线段", "射线", "以上都有"], "answer": 3, "explanation": "根据解集类型，可用点、线段、射线表示。"},
        {"question": "x > 3 在数轴上 3 用？表示", "options": ["实心点", "空心点", "箭头", "圆圈"], "answer": 1, "explanation": "不包含 3，用空心点。"},
        {"question": "x ≥ 3 在数轴上 3 用？表示", "options": ["实心点", "空心点", "箭头", "圆圈"], "answer": 0, "explanation": "包含 3，用实心点。"},
        {"question": "不等式 0 < x < 5 表示？", "options": ["x 大于 0", "x 小于 5", "x 在 0 和 5 之间", "以上都对"], "answer": 2, "explanation": "x 在 0 和 5 之间（不含端点）。"},
    ],
    "t10": [
        {"question": "二元一次方程组通常有？", "options": ["无解", "唯一解", "无穷多解", "唯一解或无解"], "answer": 1, "explanation": "两直线通常相交于一点。"},
        {"question": "代入法的核心是？", "options": ["消元", "加减", "乘除", "猜"], "answer": 0, "explanation": "代入法通过代入消去一个未知数。"},
        {"question": "加减法的核心是？", "options": ["消元", "代入", "乘除", "猜"], "answer": 0, "explanation": "加减消元法通过加减消去一个未知数。"},
        {"question": "方程组 {x=1, y=2} 满足 x+y=?", "options": ["1", "2", "3", "4"], "answer": 2, "explanation": "1+2=3。"},
        {"question": "方程组 {x+y=5, x-y=1} 的 y=?", "options": ["1", "2", "3", "4"], "answer": 1, "explanation": "两式相减：2y=4，y=2。"},
        {"question": "方程组 {2x+y=8, x+y=5} 的 x=?", "options": ["1", "2", "3", "4"], "answer": 2, "explanation": "第一式减第二式：x=3。"},
        {"question": "方程组 {x+y=3, 2x+2y=6} 有？", "options": ["唯一解", "无解", "无穷多解", "不确定"], "answer": 2, "explanation": "两方程等价（第二式是第一式的2倍），无穷多解。"},
        {"question": "方程组 {x+y=3, x+y=5} 有？", "options": ["唯一解", "无解", "无穷多解", "不确定"], "answer": 1, "explanation": "矛盾方程组，无解。"},
        {"question": "三元一次方程组需要？个方程", "options": ["1", "2", "3", "4"], "answer": 2, "explanation": "n 个未知数通常需要 n 个方程。"},
        {"question": "方程组的解要？", "options": ["代入验证", "看是否为正", "计算", "猜"], "answer": 0, "explanation": "解要代入原方程组验证。"},
        {"question": "消元法的数学依据是？", "options": ["等式性质", "不等式性质", "分配律", "交换律"], "answer": 0, "explanation": "等式两边同加减同乘除。"},
        {"question": "方程组 {x=2y, x+y=9} 的解是？", "options": ["x=3,y=6", "x=6,y=3", "x=4,y=5", "x=5,y=4"], "answer": 1, "explanation": "代入：2y+y=9，3y=9，y=3，x=6。"},
        {"question": "方程组的应用场景有？", "options": ["鸡兔同笼", "行程问题", "工程问题", "以上都是"], "answer": 3, "explanation": "方程组广泛应用于各类问题。"},
        {"question": "鸡兔同笼：头 10 脚 28，鸡？只", "options": ["4", "5", "6", "7"], "answer": 2, "explanation": "设鸡 x 兔 y：x+y=10, 2x+4y=28，解得 x=6。"},
        {"question": "方程组 {3x+2y=12, x-y=1} 的解是？", "options": ["x=2,y=3", "x=3,y=2", "x=1,y=0", "x=4,y=0"], "answer": 0, "explanation": "由第二式 x=y+1，代入第一式：3(y+1)+2y=12，5y=9..."},
        {"question": "图像法解方程组的几何意义是？", "options": ["求交点", "求距离", "求面积", "求斜率"], "answer": 0, "explanation": "方程组的解是两直线的交点。"},
    ],
}
